# Generated by Django 6.1 on 2026-08-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymenu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='categorymenu',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
