# Generated by Django 6.1 on 2026-08-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_categorymenu_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymenu',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
