# Generated by Django 6.1 on 2026-08-22 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_foodmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='food_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_category', to='menu.categorymenu'),
        ),
    ]
