# Generated by Django 6.1 on 2026-08-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_foodmenu_food_img_alter_foodmenu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
