# Generated by Django 6.1 on 2026-08-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_foodorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(blank=True, max_length=20)),
                ('qr_data', models.CharField(blank=True, max_length=255)),
                ('qr_image_url', models.ImageField(blank=True, null=True, upload_to='qr_images')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Needs-Cleaning', 'Needs-Cleaning')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
