# Generated by Django 6.1 on 2026-08-25 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_orders_tableorders_delete_foodorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorders',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='table_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='menu.tableorders'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
