# Generated by Django 6.1 on 2026-08-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_tableorders_order_orders_table_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorders',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Served', 'Served')], default='Pending', max_length=20),
        ),
    ]
