# Generated by Django 6.1 on 2026-08-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_tableorders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymenu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
