# Generated by Django 6.1 on 2026-08-26 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_categorymenu_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorders',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_given', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.orders')),
            ],
        ),
    ]
