# Generated by Django 6.1 on 2026-08-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='table_order',
        ),
    ]
