# Generated by Django 6.1 on 2026-08-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_remove_table_status_tableorders_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorders',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=20),
        ),
    ]
