# Generated by Django 6.1 on 2026-08-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_tableorders_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorders',
            name='table_status',
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Needs-Cleaning', 'Needs-Cleaning')], default='Available', max_length=20),
        ),
    ]
