# Generated by Django 6.1 on 2026-08-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_payment_cashier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
