# Generated by Django 6.1 on 2026-08-31 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_alter_table_table_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tableorders',
            options={'ordering': ['-id']},
        ),
    ]
