# Generated by Django 6.1 on 2026-09-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_alter_payment_options_alter_tableorders_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodmenu',
            options={'ordering': ['id']},
        ),
    ]
