# Generated by Django 6.1 on 2026-09-08 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_alter_foodmenu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymenu',
            options={'ordering': ['-id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='foodmenu',
            options={'ordering': ['id'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['-id'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AlterModelOptions(
            name='tableorders',
            options={'ordering': ['-id'], 'verbose_name': 'Table Order', 'verbose_name_plural': 'Table Orders'},
        ),
    ]
